### PR TITLE
New Python3 branch (by Adrian Chifor)

### PR DESCRIPTION
**Pull request by epcim**
WIP
I created this branch with "faked" commit by Adrian, as adrian:python3->reclass:python3 and then reclass:python3->reclass:develop has broken diff on GH - like 66 file changes. This is assummed to be more precise.

@adrianchifor I tried rebase your branch against develop, but it lead's to many conflicts to be resolved. Let me know if you are ok with this PR?

TODO
- add Travis ci
- verify with @cznewt 
- update contributors

### CODE REVIEW

**Comment by adrianchifor** [comment]
@epcim Good with me, thanks for doing this

**Comment by epcim** [comment]
we count to merge current develop to master tomorrow mornong. then I will merge this to develop together with other open PRsOn 12 Apr 2018 16:52, Luis Buriola <notifications@github.com> wrote:Would love to see this merged into develop as soon as possible as I'd like to use 31770c6 with python3

**Comment by adrianchifor** [comment]
@epcim Thanks a lot for merging this! Is there an ETA for when this will be on master and `reclass-1.5.2` will be out?

**Comment by epcim** [comment]
We are working on automated packaging for this reclass right now. Then we will be freer to merge it to master as components will be set to depend on the package.

I would like to see travis ci before its merge to master.

Also because of this https://github.com/salt-formulas/reclass/pull/22/files#diff-d814c7a02b2ed83acac42449af084050R32 the transition to master will probably take some time. (as this effectively break some of our models as old reclass was more benevolent and I simply have to wait until we transition to new reclass everywhere. (But rather then be blocked I would like to negotiate to internally patch it with "True" as default)

Actually when we would have any CI, than you could probably even depend on develop branch. What you think?

**Pull request merged**
