### PR TITLE
Fix class_mappings regression

### PR DESCRIPTION
**Pull request by taharah**
Resolves the regression of `class_mappings` functionality as reported by #84. 

Signed-off-by: Trevor Wood <Trevor.G.Wood@gmail.com>

### CODE REVIEW

**Comment by uberspot** [comment]
:+1: thanks a lot for this :)

**Comment by uberspot** [comment]
Sorry for the noise, but would anyone have some time to review this? 
@cznewt @fpytloun @Martin819  
:)

**Comment by jakubjosef** [comment]
Adding @epcim .

**Comment by uberspot** [comment]
@epcim or could someone else review this short change? Would be greatly appreciated. :)

**Pull request closed without merging**
