### PR TITLE
New global classes [WIP]

### PR DESCRIPTION
**Pull request by epcim**
Updates changed to add purely global class behavior:
(CC @richardfelkl)

~~Replaces #26~~
~~Implements #30~~

Depends on #33

Won't be merged before CI is added.
Update: as explained at #33 some refactoring is needed. As of now this PR has low priority.

### CODE REVIEW

**Comment by AndrewPickford** [comment]
Had a go at adding this functionality (see branch andrewp-class-name-refs) and came up with a method that doesn't require global classes. Works for me in my test use case and with the example in the docs from your new-global-classes branch.

This works by passing in the current _merge_base_ to recursive calls to _recurse_entity as a new parameter _context_ which then can be used to resolve references in class names if the _merge_base_ inside the recursive call does not contain the required key to resolve the reference. The trick was not trying to update _context_ as the _merge_base_ is updated but to try the reference render for each separately.

**Comment by epcim** [comment]
[**@AndrewPickford**](https://github.com/AndrewPickford) commented on [Apr 24, 2018, 2:49 PM GMT+2](https://github.com/salt-formulas/reclass/pull/34#issuecomment-383917871 "2018-04-24T12:49:13Z - Replied by Github Reply Comments"):
> Had a go at adding this functionality (see branch andrewp-class-name-refs) and came up with a method that doesn't require global classes. Works for me in my test use case and with the example in the docs from your new-global-classes branch.
> 
> This works by passing in the current _merge_base_ to recursive calls to _recurse_entity as a new parameter _context_ which then can be used to resolve references in class names if the _merge_base_ inside the recursive call does not contain the required key to resolve the reference. The trick was not trying to update _context_ as the _merge_base_ is updated but to try the reference render for each separately.

I see Nice! I bit missed a point where recursive descent happen, otherwise I would do it that way either. My proposal - I will check that with my model. If passing I will review your code again and probably will rather go your way - as that implements clean overriding and propagation without a need for global-class construct. Regarding global classes - we actually have edge use-case for them as well and I mixed that in one commit, so I will send it as a separate patch.

**Comment by epcim** [comment]
We have identified a requirement for this feature. So we count with rebase + merging it (by default disabled). Just to be sure - anyone with the beter idea (for conditional, or any occurance class loading (not just first time seen?)

**Comment by AndrewPickford** [comment]
@epcim Could you expand on the use case? From the changes to the readme it looks like you want a parameter that cannot be overridden.

I've been thinking about adding other qualifiers to keys (other than ~ to force an overwrite) but yaml reserves most of the usual punctuation characters. However '=' isn't reserved so we could do:

```yaml
parameter:
  =fixed: 'can not be changed'
```

to indicate that an error should be raised if a parameter would be changed.

This would remove the need to reload a class each time it's seen which gets rid of the need to add the special case coding in reclass/datatypes/parameters.py. It's the changes here that look as if they could have some unintended consequences.

**Comment by richardfelkl** [comment]
@AndrewPickford sometimes the class reload is needed. For example if one node includes two classes (A then B). Classes C and D sets patameter P=true. Class E sets P= false. Class A includes class C then E, class B includes D then E. When Reclass processes the node's class A it sets P=false then it starts processing B it takes class D and sets P=true again then skips class E because it has already been processed on this node and P results in undesired state.

If class was processed each time it is specified this behavior won't happen. I think it won't break anything if this option is disabled by default because of performance issues and it can be enabled if needed.

**Comment by AndrewPickford** [comment]
@richardfelkl - Thanks for the example, I didn't really understand the problem before. For the specific example you could solve this without any global classes, for example extract all the commonality (including the P=true parameter) in classes C and D into a separate class F and either include class F as part of classes C and D or as part of classes A and B. This would ensure the setting of parameter P=true only happens once and then class E would correctly overwrite to P=false as part of class A. Is that of any practical help? It's a straightforward fix for the example but real world configs tend to be more messy.

By changing the same parmeter in the chains of classes loaded by both classes A and B you're setting up these sorts of nasty issues which are working against the processing flow in reclass. This also applies to including the same class E in the chain of classes included by A and B. Other than simple data defining classes (with parameters that never get over written) and classes that are explicitly constructed to take advantage of the single loading rule then I've found including the same class across separate class hierarchies leads to config structures that are both harder to make work and harder to understand.

I've bumped up against this a bit when assigning multiple roles to a single node. Say it's reasonable to define a node that includes class A, a node that includes class B and a node that includes A and B. Here I'm thinking of classes A and B as defining machine roles and that it's sensible to have a node that does both roles. One thing I've found that helps here is not to include classes A and B directly in the node doing both roles. Instead include a new class that includes A and B and then adds any configuration required as a consequence of including both A and B.

Finally loading some classes each time they are seen means the valuelist objects created for each parameter in the class will be extended each time the class is processed. For scalars and dictionaries this should just be a performance issue (and maybe not an important one) but for lists this breaks list merging. Each time the class is loaded this would merge the contents of any newly loaded lists onto the ends of their current values. The patch tries to get around this by checking for identical parameter values in the parameter._update_value method but from the integration tests this is breaking other things.

**Comment by richardfelkl** [comment]
@AndrewPickford I understand that but our use case requires such complicated Reclass model. It's pretty common to have 10-20 roles for each node and each or this role requires some global parameters from some common classes. The problem is that we don't assign many classes to each node specifically but we add 2-3 classes per node and those add pretty complicated functionality. Because of this is not easy to refactor our models and this option or at least some similar solution would be appreciated from our side.

**Comment by epcim** [comment]
Close in favor of #54

**Pull request closed without merging**
