### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by cznewt**

### CODE REVIEW

**Comment by epcim** [comment]
Looks good, but we need PR against "develop" branch where the other features are already waiting...

**Comment by michaelkuty** [comment]
I think, that the develop branch should be rebased to this PR.

**Comment by epcim** [comment]
I know we did some commits directly to master, but for past months we agreed to stack-up other developers features on develop branch that we one day merge to master as the cleanest workflow. As of now develop count 180 commits above the master.

Note develop was already merged to master, but reverted shortly before xmass due issue 14.

**Comment by adrianchifor** [comment]
Any update on this?

**Comment by epcim** [comment]
> Any update on this?

must be rebased against develop (there are many commits with features that in days will land in "master")

**Comment by AndrewPickford** [comment]
The changes should not penalise python2 users. For example the change of iteritems() to items() will be inefficient in python2. Better (at least according to http://python-future.org/compatible_idioms.html)  to use the iteritems function:

```python
from six import iteritems
for (key, value) in iteritems(dictionary):
```

**Comment by adrianchifor** [comment]
https://github.com/salt-formulas/reclass/pull/23 to speed this up

**Comment by epcim** [comment]
GH has broken diff "again". Feel free to revert here. I would suggest moving focus to #25 and close this PR.

**Comment by epcim** [comment]
Closed in favor of #25

**Pull request closed without merging**
